AWSTemplateFormatVersion: 2010-09-09
Description: Core template. Contains network and iam roles
Parameters:
  VpcCidr:
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: "10.0.0.0/16"
  Environment:
    Type: String
    AllowedValues: [ prod, test ]
    Default: prod
Conditions:
  ProdEnv: !Equals [ !Ref Environment, prod ]
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      # Indicates whether the instances launched in the VPC get DNS hostnames.
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, vpc ]