AWSTemplateFormatVersion: 2010-09-09
Description: Core template. Contains network and iam roles
Parameters:
  VpcCidr:
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: "10.0.0.0/16"
  Environment:
    Type: String
    AllowedValues: [ prod, test ]
    Default: prod
Conditions:
  ProdEnv: !Equals [ !Ref Environment, prod ]
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      # Indicates whether the instances launched in the VPC get DNS hostnames.
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, vpc ]
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 0
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, public-subnet01 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: false
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 1
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, public-subnet02 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: false
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 2
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, public-subnet03 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: false
  WebTierSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 3
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, webtier-subnet01 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  WebTierSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 4
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, webtier-subnet02 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  WebTierSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 5
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, webtier-subnet03 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  MiddlewareSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 6
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, middleware-subnet01 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  MiddlewareSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 7
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, middleware-subnet02 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  MiddlewareSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 8
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
        - Value: !Join
            - "-"
            - [ !Ref Environment, middleware-subnet03 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  DatabaseSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 9
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, database-subnet01 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  DatabaseSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 10
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, database-subnet02 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  DatabaseSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Select
        - 11
        - !Cidr [ !Ref VpcCidr, 12, 8 ]
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - [ !Ref Environment, database-subnet03 ]
        - Key: Env
          Value: !Ref Environment
        - Key: Private
          Value: true
  Igw:
    Type: AWS::EC2::InternetGateway
  IgwToVpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Igw
      VpcId: !Ref Vpc
  NatEip:
    Type: AWS::EC2::EIP
  NatGw:
    # https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html
    # A NAT gateway is a Network Address Translation service.
    # You can use a NAT gateway so that instances in a private subnet can connect to services outside your VPC
    # but external services cannot initiate a connection with those instances.
    # https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref PublicSubnet1
