AWSTemplateFormatVersion: 2010-09-09
Description: Core template. Contains network and iam roles
Parameters:
  VpcCidr:
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: "10.0.0.0/16"
  Environment:
    Type: String
    AllowedValues: [ prod, test ]
    Default: prod