version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli cfn-lint
  build:
    commands:
      - aws cloudformation validate-template --template-body file://core.yaml
  post_build:
    commands:
      - aws cloudformation deploy --template-file core.yaml --stack-name core-tmp --capabilities CAPABILITY_NAMED_IAM --role-arn $CFN_ROLE
    finally:
      - aws cloudformation describe-stack-events --stack-name core-tmp
      - aws cloudformation delete-stack --stack-name core-tmp --role-arn $CFN_ROLE
artifacts:
  files:
    - core.yaml