AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline template for DevOps
Resources:
  CfnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  TemplateBucket:
    Type: AWS::S3::Bucket
    Description: The S3 bucket used for storing the artifact for a pipeline.
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - codecommit:GitPull
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - cloudformation:*
                  - iam:PassRole
                  - ec2:Describe*
                Resource: "*"
          PolicyName: BuildPolicy