AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline template for DevOps
Resources:
  CfnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  TemplateBucket:
    Type: AWS::S3::Bucket
    Description: The S3 bucket used for storing the artifact for a pipeline.
