AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline template for DevOps
Parameters:
  CfnStackName:
    Type: String
    Description: Name of the CFN stack to deploy.
    Default: Core
Resources:
  CfnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: core
  TemplateBucket:
    Type: AWS::S3::Bucket
    Description: The S3 bucket used for storing the artifact for a pipeline.
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - codecommit:GitPull
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - cloudformation:*
                  - iam:PassRole
                  - ec2:Describe*
                Resource: "*"
          PolicyName: BuildPolicy
  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      # Artifacts is a property of the AWS:CodeBuild::Project resource
      # that specifies output settings for artifacts generated by an AWS CodeBuild build.
      Artifacts:
        # The type of build output artifact. Valid values include:
        # CODEPIPELINE: The build project has build output generated through CodePipeline
        # NO_ARTIFACTS: The build project does not produce any build output.
        # S3: The build project stores build output in Amazon S3
        Type: CODEPIPELINE
      ServiceRole: !GetAtt BuildRole.Arn
      Name: Core
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        EnvironmentVariables:
          - Name: CFN_ROLE
            Type: PLAINTEXT
            Value: !GetAtt CfnRole.Arn
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipeline
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - cloudwatch:*
                  - cloudformation:*
                  - s3:*
                  - iam:PassRole
                Resource: '*'
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Location: !Ref TemplateBucket
        Type: S3
      Name: Core
      Stages:
        # https://github.com/symphoniacloud/github-codepipeline/blob/master/pipeline.yaml
        # ThirdParty Source
        - Name: Clone
          Actions:
            - Name: Clone
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              OutputArtifacts:
                - Name: CloneOutput
              Configuration:
                BranchName: main
                RepositoryName: !GetAtt Repository.Name
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: CloneOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref Build
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: BuildOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              OutputArtifacts:
                - Name: DeployOutput
              # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CfnRole.Arn
                # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html
                # For stacks that contain certain resources, explicit acknowledgement that AWS CloudFormation might create or update those resources.
                # https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Ref CfnStackName
                TemplatePath: BuildOutput::core.yaml